### ISSUE TITLE
【BUG】单机多卡LLaMa2失败

### ISSUE THREAD

**Issue by glen-nascentcoreai** [NascentCore/3k#197]
**Describe the bug**
```
glen@worker4:~/llama2$
glen@worker4:~/llama2$ export MASTER_ADDR="214.2.5.4" MASTER_PORT=29501 NCCL_DEBUG=INFO NCCL_NET=IB NCCL_P2P_LEVEL=SYS NCCL_NET_GDR_READ=1 NCCL_IB_CUDA_SUPPORT=1 NCCL_NET_GDR_LEVEL=SYS NCCL_IB_GDR_LEVEL=SYS NCCL_DEBUG_SUBSYS=ALL NCCL_SOCKET_IFNAME=ibs1 NCCL_IB_HCA=mlx5_
glen@worker4:~/llama2$
glen@worker4:~/llama2$
glen@worker4:~/llama2$ python3 -m torch.distributed.launch --nproc-per-node=8 --nnodes=1 --node_rank=0 --master-addr="214.2.5.4" --master-port=29501 llama2_demo.py
/home/glen/.local/lib/python3.8/site-packages/torch/distributed/launch.py:181: FutureWarning: The module torch.distributed.launch is deprecated
and will be removed in future. Use torchrun.
Note that --use-env is set by default in torchrun.
If your script expects `--local-rank` argument to be set, please
change it to read from `os.environ['LOCAL_RANK']` instead. See
https://pytorch.org/docs/stable/distributed.html#launch-utility for
further instructions

  warnings.warn(
[2023-10-28 02:54:18,196] torch.distributed.run: [WARNING]
[2023-10-28 02:54:18,196] torch.distributed.run: [WARNING] *****************************************
[2023-10-28 02:54:18,196] torch.distributed.run: [WARNING] Setting OMP_NUM_THREADS environment variable for each process to be 1 in default, to avoid your system being overloaded, please further tune the variable for optimal performance in your application as needed.
[2023-10-28 02:54:18,196] torch.distributed.run: [WARNING] *****************************************
[2023-10-28 02:54:19,985] [INFO] [real_accelerator.py:158:get_accelerator] Setting ds_accelerator to cuda (auto detect)
[2023-10-28 02:54:20,000] [INFO] [real_accelerator.py:158:get_accelerator] Setting ds_accelerator to cuda (auto detect)
[2023-10-28 02:54:20,004] [INFO] [real_accelerator.py:158:get_accelerator] Setting ds_accelerator to cuda (auto detect)
[2023-10-28 02:54:20,008] [INFO] [real_accelerator.py:158:get_accelerator] Setting ds_accelerator to cuda (auto detect)
[2023-10-28 02:54:20,012] [INFO] [real_accelerator.py:158:get_accelerator] Setting ds_accelerator to cuda (auto detect)
[2023-10-28 02:54:20,013] [INFO] [real_accelerator.py:158:get_accelerator] Setting ds_accelerator to cuda (auto detect)
[2023-10-28 02:54:20,019] [INFO] [real_accelerator.py:158:get_accelerator] Setting ds_accelerator to cuda (auto detect)
[2023-10-28 02:54:20,020] [INFO] [real_accelerator.py:158:get_accelerator] Setting ds_accelerator to cuda (auto detect)
WORLD_SIZE: 8
Current global rank: 6
Current local rank: 6
WORLD_SIZE: 8
Current global rank: 3
Current local rank: 3
WORLD_SIZE: 8
Current global rank: 7
Current local rank: 7
WORLD_SIZE: 8
Current global rank: 4
Current local rank: 4
WORLD_SIZE: 8
Current global rank: 1
Current local rank: 1
WORLD_SIZE: 8
Current global rank: 2
Current local rank: 2
WORLD_SIZE: 8
Current global rank: 0
WORLD_SIZE: 8
Current global rank: 5
Current local rank: 0
Current local rank: 5







Detected kernel version 5.4.0, which is below the recommended minimum of 5.5.0; this can cause the process to hang. It is recommended to upgrade the kernel to the minimum version or higher.
Begin training...
Begin training...
Begin training...
Begin training...
[2023-10-28 02:56:06,971] [INFO] [logging.py:96:log_dist] [Rank -1] DeepSpeed info: version=0.11.1, git-hash=unknown, git-branch=unknown
[2023-10-28 02:56:06,971] [INFO] [comm.py:637:init_distributed] cdb=None
worker4:23818:23818 [0] NCCL INFO NCCL_SOCKET_IFNAME set by environment to ibs1
worker4:23818:23818 [0] NCCL INFO NCCL_SOCKET_IFNAME set to ibs1

worker4:23818:23818 [0] bootstrap.cc:45 NCCL WARN Bootstrap : no socket interface found
worker4:23818:23818 [0] NCCL INFO init.cc:82 -> 3
worker4:23818:23818 [0] NCCL INFO init.cc:101 -> 3
Traceback (most recent call last):
  File "llama2_demo.py", line 200, in <module>
    trainer.train()
  File "/home/glen/.local/lib/python3.8/site-packages/transformers/trainer.py", line 1539, in train
    return inner_training_loop(
  File "/home/glen/.local/lib/python3.8/site-packages/transformers/trainer.py", line 1659, in _inner_training_loop
    model, self.optimizer, self.lr_scheduler = self.accelerator.prepare(
  File "/home/glen/.local/lib/python3.8/site-packages/accelerate/accelerator.py", line 1284, in prepare
    result = self._prepare_deepspeed(*args)
  File "/home/glen/.local/lib/python3.8/site-packages/accelerate/accelerator.py", line 1666, in _prepare_deepspeed
    engine, optimizer, _, lr_scheduler = deepspeed.initialize(**kwargs)
  File "/home/glen/.local/lib/python3.8/site-packages/deepspeed/__init__.py", line 171, in initialize
    engine = DeepSpeedEngine(args=args,
  File "/home/glen/.local/lib/python3.8/site-packages/deepspeed/runtime/engine.py", line 262, in __init__
    self._configure_distributed_model(model)
  File "/home/glen/.local/lib/python3.8/site-packages/deepspeed/runtime/engine.py", line 1119, in _configure_distributed_model
    self._broadcast_model()
  File "/home/glen/.local/lib/python3.8/site-packages/deepspeed/runtime/engine.py", line 1042, in _broadcast_model
    dist.broadcast(p, groups._get_broadcast_src_rank(), group=self.seq_data_parallel_group)
  File "/home/glen/.local/lib/python3.8/site-packages/deepspeed/comm/comm.py", line 117, in log_wrapper
    return func(*args, **kwargs)
  File "/home/glen/.local/lib/python3.8/site-packages/deepspeed/comm/comm.py", line 224, in broadcast
    return cdb.broadcast(tensor=tensor, src=src, group=group, async_op=async_op)
  File "/home/glen/.local/lib/python3.8/site-packages/deepspeed/comm/torch.py", line 196, in broadcast
    return torch.distributed.broadcast(tensor=tensor, src=src, group=group, async_op=async_op)
  File "/home/glen/.local/lib/python3.8/site-packages/torch/distributed/c10d_logger.py", line 47, in wrapper
    return func(*args, **kwargs)
  File "/home/glen/.local/lib/python3.8/site-packages/torch/distributed/distributed_c10d.py", line 1910, in broadcast
    work = group.broadcast([tensor], opts)
torch.distributed.DistBackendError: NCCL error in: ../torch/csrc/distributed/c10d/ProcessGroupNCCL.cpp:1249, internal error - please report this issue to the NCCL developers, NCCL version 2.18.1
ncclInternalError: Internal check failed.
Last error:
Bootstrap : no socket interface found
Begin training...
Begin training...
[2023-10-28 02:56:13,393] torch.distributed.elastic.multiprocessing.api: [WARNING] Sending process 23819 closing signal SIGTERM
[2023-10-28 02:56:13,393] torch.distributed.elastic.multiprocessing.api: [WARNING] Sending process 23820 closing signal SIGTERM
[2023-10-28 02:56:13,394] torch.distributed.elastic.multiprocessing.api: [WARNING] Sending process 23821 closing signal SIGTERM
[2023-10-28 02:56:13,394] torch.distributed.elastic.multiprocessing.api: [WARNING] Sending process 23822 closing signal SIGTERM
[2023-10-28 02:56:13,394] torch.distributed.elastic.multiprocessing.api: [WARNING] Sending process 23824 closing signal SIGTERM
[2023-10-28 02:56:13,394] torch.distributed.elastic.multiprocessing.api: [WARNING] Sending process 23826 closing signal SIGTERM
[2023-10-28 02:56:13,395] torch.distributed.elastic.multiprocessing.api: [WARNING] Sending process 23827 closing signal SIGTERM
[2023-10-28 02:56:14,674] torch.distributed.elastic.multiprocessing.api: [ERROR] failed (exitcode: 1) local_rank: 0 (pid: 23818) of binary: /usr/bin/python3
Traceback (most recent call last):
  File "/usr/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/home/glen/.local/lib/python3.8/site-packages/torch/distributed/launch.py", line 196, in <module>
    main()
  File "/home/glen/.local/lib/python3.8/site-packages/torch/distributed/launch.py", line 192, in main
    launch(args)
  File "/home/glen/.local/lib/python3.8/site-packages/torch/distributed/launch.py", line 177, in launch
    run(args)
  File "/home/glen/.local/lib/python3.8/site-packages/torch/distributed/run.py", line 797, in run
    elastic_launch(
  File "/home/glen/.local/lib/python3.8/site-packages/torch/distributed/launcher/api.py", line 134, in __call__
    return launch_agent(self._config, self._entrypoint, list(args))
  File "/home/glen/.local/lib/python3.8/site-packages/torch/distributed/launcher/api.py", line 264, in launch_agent
    raise ChildFailedError(
torch.distributed.elastic.multiprocessing.errors.ChildFailedError:
============================================================
llama2_demo.py FAILED
------------------------------------------------------------
Failures:
  <NO_OTHER_FAILURES>
------------------------------------------------------------
Root Cause (first observed failure):
[0]:
  time      : 2023-10-28_02:56:13
  host      : worker4
  rank      : 0 (local_rank: 0)
  exitcode  : 1 (pid: 23818)
  error_file: <N/A>
  traceback : To enable traceback see: https://pytorch.org/docs/stable/elastic/errors.html
============================================================
glen@worker4:~/llama2$
```

**To Reproduce**

**Expected behavior**

**Screenshots**

**Additional context**

**Comment by glen-nascentcoreai** [comment]
```
glen@worker4:~$
glen@worker4:~$ ibdev2netdev -v
cat: /sys/class/infiniband/mlx5_0/device/vpd: Permission denied
0000:1d:00.0 mlx5_0 (MT4123 -            )                 fw 20.34.1002 port 1 (ACTIVE) ==> ibs10 (Down)
cat: /sys/class/infiniband/mlx5_1/device/vpd: Permission denied
0000:45:00.0 mlx5_1 (MT4123 -            )                 fw 20.34.1002 port 1 (ACTIVE) ==> ibs11 (Down)
cat: /sys/class/infiniband/mlx5_2/device/vpd: Permission denied
0000:96:00.0 mlx5_2 (MT4123 -            )                 fw 20.32.2004 port 1 (ACTIVE) ==> ibs18 (Down)
cat: /sys/class/infiniband/mlx5_3/device/vpd: Permission denied
0000:cd:00.0 mlx5_3 (MT4123 -            )                 fw 20.34.1002 port 1 (ACTIVE) ==> ibs19 (Down)
glen@worker4:~$
glen@worker4:~$
glen@worker4:~$
glen@worker4:~$ sudo ibdev2netdev -v
[sudo] password for glen:
0000:1d:00.0 mlx5_0 (MT4123 - 1028SN     ) Mellanox ConnectX-6 Single Port VPI HDR QSFP Adapter fw 20.34.1002 port 1 (ACTIVE) ==> ibs10 (Down)
0000:45:00.0 mlx5_1 (MT4123 - 1028SN     ) Mellanox ConnectX-6 Single Port VPI HDR QSFP Adapter fw 20.34.1002 port 1 (ACTIVE) ==> ibs11 (Down)
0000:96:00.0 mlx5_2 (MT4123 - 1028SN     ) Mellanox ConnectX-6 Single Port VPI HDR QSFP Adapter fw 20.32.2004 port 1 (ACTIVE) ==> ibs18 (Down)
0000:cd:00.0 mlx5_3 (MT4123 - 1028SN     ) Mellanox ConnectX-6 Single Port VPI HDR QSFP Adapter fw 20.34.1002 port 1 (ACTIVE) ==> ibs19 (Down)
glen@worker4:~$
```

**Comment by glen-nascentcoreai** [comment]
https://github.com/Mellanox/container_scripts/blob/3dcfee08a89c0386a77e1a06d9ef51bdd754a0f4/ibdev2netdev#L120

```
						filepath_carrier=/sys/class/net/$eth/carrier

						if [ -f $filepath_carrier ]; then
							link_state=$(cat $filepath_carrier 2> /dev/null)
        	                                        if (( link_state == 1 )); then
                	                                        link_state="Up"
                        	                        else
                                	                        link_state="Down"
                                        	        fi
						else
							link_state="NA"
						fi
```

**Comment by glen-nascentcoreai** [comment]
https://www.kernel.org/doc/Documentation/ABI/testing/sysfs-class-net
```
What:		/sys/class/net/<iface>/carrier
Date:		April 2005
KernelVersion:	2.6.12
Contact:	netdev@vger.kernel.org
Description:
		Indicates the current physical link state of the interface.
		Possible values are:

		== =====================
		0  physical link is down
		1  physical link is up
		== =====================

		Note: some special devices, e.g: bonding and team drivers will
		allow this attribute to be written to force a link state for
		operating correctly and designating another fallback interface.
```
